[features]
seeds = false
[programs.localnet]
exhibition = "9U8mXG1EqABTdERF3kA9JdnYaHirs4YsQDta2xzHjbPq"
bazaar = "C71P9khhQ23ufjqBW6EvtN79CgXT5tPB73LKcTxtPPTC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/harshasomisetty/.config/solana/creator.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/bazaar.ts"

[test.validator]    
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "p1exdMJcjVao65QdewkaZRUnU6VPSXhus9n2GzWfh98"

[[test.validator.clone]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"
